// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozcehnapenmgnamnkome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Y2VobmFwZW5tZ25hbW5rb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzgxODAsImV4cCI6MjA2NTUxNDE4MH0.EQlQ-C_NOovx2_k-XJKWHa84UUi-d_WWnT7GhG7Wq-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);